// src/pages/legal/TermsOfService.jsx
import MarketingNav    from '../../components/marketing/MarketingNav';
import MarketingFooter from '../../components/marketing/MarketingFooter';

export default function TermsOfService() {
  return (
    <div className="min-h-screen flex flex-col">
      <MarketingNav />
      <div className="flex-1 max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-serif text-4xl font-bold text-brand-dark mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        <div className="space-y-8 text-gray-700 text-sm leading-relaxed">
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">1. Acceptance</h2><p>By creating a TaxStory account or using any TaxStory service, you agree to these Terms of Service. TaxStory is operated by Lakeside Advisory Group, LLC.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">2. Service description</h2><p>TaxStory provides AI-powered tax return video generation and multi-year tax projection tools for CPAs and Registered Investment Advisors. The platform processes tax return data using a PII-free architecture and generates client-facing content using artificial intelligence.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">3. Not tax or financial advice</h2><p>TaxStory is a communication and projection tool only. Nothing generated by TaxStory constitutes tax advice, financial advice, or legal advice. All client-facing content generated by TaxStory is the responsibility of the professional user who reviews and delivers it.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">4. Acceptable use</h2><p>You agree to: only upload tax returns for which you have authorization, not attempt to extract or circumvent our PII-free architecture, comply with applicable professional regulations (IRS Circular 230, state CPA licensing, SEC/FINRA regulations), and not share your account credentials with other users.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">5. Subscription and billing</h2><p>Subscriptions begin with a 14-day free trial. After the trial, you will be charged according to your selected plan. Annual subscriptions are billed upfront. Unused projections and video credits do not roll over between subscription periods. Refunds are not provided for partial periods.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">6. Limitation of liability</h2><p>To the maximum extent permitted by law, Lakeside Advisory Group, LLC shall not be liable for any indirect, incidental, special, or consequential damages arising from use of TaxStory.</p></section>
          <section><h2 className="font-semibold text-brand-dark text-xl mb-3">7. Contact</h2><p>Legal questions: <a href="mailto:legal@tellmytaxstory.com" className="text-brand-purple underline">legal@tellmytaxstory.com</a></p></section>
        </div>
      </div>
      <MarketingFooter />
    </div>
  );
}
